### PR TITLE
feat: ability to customize buffer indicators

### PR DESCRIPTION
**Pull request by dlvhdr**
image

- feat: ability to set buffer indicators
- refactor: rename and docs

### CODE REVIEW

**Comment by dlvhdr** [comment]
Hey @danielfalk is this something you'd like merged?

**Comment by danielfalk** [comment]
Yes, the code looks good. Thanks.  Just as a side note, I want to be more careful than I have before when it comes to adding configuration.  I know this goes against the community's desire to customize every last thing.  But for me, I'd rather provide defaults that work really well when possible.  Partially that's because there are more possible combinations of setups to test, and also because then the plugin is more complicated to setup and use than necessary. I think some of the options that are already there probably shouldn't be but once you put them in, taking them out and simplifying becomes a breaking change.

Anyway, I'm merging this and I appreciate the contribution.  I just wanted to put that out there.

**Comment by dlvhdr** [comment]
Agree. Just to add my 2 cents that I found the default icons to be tiny and hard to distinguish between them

**Comment by cshuaimin** [comment]
> provide defaults that work really well

That's amazing, totally agree with you!

**Pull request merged**
