### PR TITLE
feat: filename_first option

### PR DESCRIPTION
**Pull request by YodaEmbedding**

### CODE REVIEW

**Comment by danielfalk** [comment]
The code looks right, but I don't have time to test this yet.  I'm particularly concerned with the highlighting.  Does it look OK in all circumstances?

**Comment by YodaEmbedding** [comment]
When `filename_first = false`, the highlighting is 1 character too long:

**Comment by YodaEmbedding** [comment]
Fixed:

**Comment by YodaEmbedding** [comment]
The search highlighting isn't working properly for directories, though.

**Comment by YodaEmbedding** [comment]
Fixed in https://github.com/danielfalk/smart-open.nvim/pull/37/commits/a961ee00c6447d813ba935481d22345f38dc1177:



---

P.S. The highlighting for both `filename_first = true` and `filename_first = false` is slightly technically inaccurate when the path is shortened with `...`, but that would require a deeper rewrite to "fix", outside the scope of this PR.

**Comment by danielfalk** [comment]
Good work first of all.  I was able to try it out.  There is just one remaining thing I noticed.  With `filename_first = true`, there is no leading slash for files in the base directory, but for `filename_first = false`, I'm seeing that:
image

(should just be `stylua.toml`, not `/stylua.toml`)

**Comment by YodaEmbedding** [comment]
Fixed in https://github.com/danielfalk/smart-open.nvim/pull/37/commits/92e523a228524f40b9b2414efc27b2cce4fcef6c.

---

I think that the path formatters may need more tweaking. For instance, given the directory tree:

```
~/cwd/
     ├── cwd
     │   ├── init.lua
     │   └── not_an_init.txt
     ├── init.lua
     └── not_an_init.txt
```

And if `cwd = ~/cwd`, then we get:





Notice that `~/cwd/init.lua` is formatted a bit confusingly in both cases and could be confused with `~/cwd/cwd/init.lua`. Not sure what would make sense as an alternative... but perhaps it's outside the scope of this PR.

**Comment by YodaEmbedding** [comment]
I think that the path formatters may need more tweaking. For instance, given the directory tree:

```
~/cwd/
     ├── cwd
     │   ├── init.lua
     │   └── not_an_init.txt
     ├── init.lua
     └── not_an_init.txt
```

And if `cwd = ~/cwd`, then we get:





Notice that `~/cwd/init.lua` is formatted a bit confusingly in both cases and could be confused with `~/cwd/cwd/init.lua`. Not sure what would make sense as an alternative... but perhaps it's outside the scope of this PR.

**Pull request merged**
